cylc/cylc-admin

dec-workshop-agenda.md

AIOHTTP is also a good candidate to consider for web server. Its demos have examples on WebSocket and GraphQL usages.

Add AIOHTTP as alternative server framework

---

docs/cylc-8-tasks.md

Update to the 'Cylc 8 Implementation Task List' document:
* mark the documentation conversion as completed (:ballot_box_with_check:);
* add in indicators against tasks I would personally like to sign up to to work on (at whatever time they become doable & are given priority)[*].
[*]: of course this is as a preference & if in practice it is best for others to do these, that is fine; I would simply like to register that I would like to work on these if possible.

Mark docs conversion as complete + further assignments

---

docs/vc-march-2019-agenda.md

Quick pull request with a suggestion for coding conventions for our repositories. Our Python code is being rewritten in some packages, so this is a good time to establish code conventions to be followed.
These conventions could also be re-used in the Cylc UI Server and other Python projects.
There are already a few docstrings, but some in the google format, some in the old PEP 257, some in the docstring supported by PyCharm (_cough, cough_, sorry).
I think ideally we need one that can be used for documentation, but also by syntax highlighters and IDE's - the more tools supported, the merrier IMO.
Cheers
Bruno

Suggest coding styles for the meeting agenda of Mar/2019

---

docs/meetings/vc-4-apr-2019-agenda.md

Messed up the format. It was due to using an indented list in Markdown, whose parent was a paragraph, and not another list.
Tested here to make sure it works: https://kinow.github.io/cylc-admin/meetings/vc-4-apr-2019-agenda.html

Fix formatting

---

docs/security-discussions.md

Follow up after [discussion](https://github.com/cylc/cylc-admin/issues/11#issuecomment-486932148) around the newly created `SECURITY.md`.

Add security discussions document

---

docs/index.md

Sorry, I have realised a relative link I added in #41 to the index listing of Cylc Admin documents is broken (try the [last bullet here](https://cylc.github.io/cylc-admin/#cylc-8-work-in-progress)). I went it to fix it & whilst quickly checking all the other links in the index worked, noticed there was a duplicate entry, where one was marked as outdated, but the other (see the line directly above) not so. This PR fixes both aspects. 
Trivial hence one reviewer sufficient.

Fix broken, & remove duplicate, link in index list

---

docs/index.md

Mistakenly committed these docs without index refs to them.

Rose-suite-run migration docs added to index

---

docs/index.md
docs/proposal-state-names.md

REF: https://github.com/cylc/cylc-ui/pulls#issuecomment-521121132 (and follow-up comment from @matthewrmshin )
*Cylc has gradually accrued new task states and associated triggers and outputs over the years, and the resulting names are variously ambiguous, confusing, or grammatically inconsistent.*

Task state, trigger, and output name rationalization proposal

---

docs/proposal-platforms.md
docs/proposal-rose-suite-run.md
docs/rose-suite-run-proposal/cylc-flow-rc.md

Re-write of the rose suite-run proposal. The initial focus of the work will be implementing support for platforms which is now described in detail in a separate document.

Update the rose-suite-run proposal and add a separate platforms proposal

---

docs/proposal-platforms.md

Platform aliases were originally a new subsection each containing 1 item. Why not just have those items in the section above?

Platform aliases don't need extra level

---

docs/proposal-multi-user-approach.rst

I think this is a decision we have already unconsciously made but one we have no record of?
Push multi-user functionality out of Cylc Flow and into the UI Server.
Formally retire the *requirement* for port scanning, anomalous authentication, etc.

proposal: mutl-user functionaltiy + cylc flow

---

docs/proposal-platforms.md

Put each alias in a section of its own so we can configure load balancing (which would finally make `rose host-select` redundant).
```ini
[platform aliases]
[[<alias name>]]
platforms = list, of, platforms
ranking = """
virtual_memory().available
getloadavg()[0] < 1
"""
```

platforms: leave room for rose host-select migration

---

docs/cylc-8-architecture.md
docs/cylc-8-roadmap.md
docs/dec-workshop-agenda.md
docs/feb2020-workshop-agenda.md
docs/feb2020-workshop-notes.md
docs/feb2020-workshop-report.md
docs/gui-replacement-options.md
docs/howto/create-a-release.md
docs/index.md
docs/meetings/vc-4-apr-2019-summary.md
docs/meetings/vc-8-oct-2019-agenda.md
docs/meetings/vc-9-aug-2019-summary.md
docs/meetings/vc-9-sep-2019-agenda.md
docs/meetings/vc-9-sep-2019-notes.md
docs/meetings/vc-april-2020.md
docs/meetings/vc-mar-2019-agenda.md
docs/meetings/vc-may-2020.md
docs/practices-prompts.md
docs/proposal-cli-wfs-authentication.md
docs/proposal-platforms.md
docs/proposal-state-names.md
docs/release-notes/cylc-8-alpha2.md
docs/rose-suite-run-proposal/cylc-flow-rc.md
docs/rose-suite-run-proposal/tickets.md
docs/spawn-on-submit-history.md
docs/threats.md
docs/user-research/20190606-suites-guild-cylc-gui-review.md
docs/user-research/MO-user-groups-feedback.md
docs/user-research/ur-initiation-questions.md
docs/user-research/ur-meetings/ur-04-june-2019-summary.md

Remembered that when reading the Conda notes this morning, didn't find the `--use-local` in the docs.
Reading the release notes in our site, noted that one markdown link (what's new) was broken.
And the IDE found some typos, so just applied its suggestions.
:+1: nothing critical here, doesn't need to be reviewed or merged before our release.

Fix markdown link in Cylc 8 release and typos

---

docs/howto/create-a-release.md
docs/project-collab.md

Going through my notes taken during our latest release. In one release doc we had Riot I think, so tried to replace the occurrences that were not meeting minutes (no point in update those I think) and update Riot -> Element.
Also replaced Google Groups by Discourse in the collab document. One review should do.

Riot is now Element

---

docs/proposal-spawn-on-d.md

Two new commits.
- The first commit documents exactly how suicide triggers work under SoD (after an email from @dpmatthews)
- The second commit documents the new handling of absolute triggers (after SoD review comments from @dwsutherland)
Both add minor items to the TODO list, to be converted to issues after the SoD PR is merged.

SoD proposal/doc update.

---

docs/release-notes/cylc-8-alpha2.md

Tell users how to test Cylc 8 without a central wrapper script (local background jobs) and under what circumstances they may need to disable their Cylc 7 wrapper script to do so.

Add cylc wrapper warning to a2 release notes.

---

docs/proposal-platforms.md

* Remove support for rsync filter files.
It's better to support a single way of specifying what needs to be installed via `cylc.flow`.
rsync filter files would have allowed excludes as well as includes but we don't really need these.
Note that cylc 7 suites which rely on the installation of directories other than `app/ bin/ etc/ lib` will need `[scheduler]install` to be defined appropriately before they will work at cylc 8.
* Allow the default set of directories to be installed to be overridden.
* The proposal remains to install the same files to all targets.
We could consider adding support for installing on a task / platform basis later (if we decide this is required / makes sense) via a task level setting, e.g.
```ini
[runtime]
[[task]]
platform = myplatform
install = ...
```

platforms proposal: tweak installation method

---

docs/howto/create-a-release.md

Because cylc-doc autodocuments other projects it is necessary to test that the docs build correctly before releasing any of these documented projects. Otherwise we will have to re-release in order to fix little things like broken urls.
These breakages should get picked up by our nightly testing (when we get that off the ground), however, this is a quick simple check which should be worthwhile.

add instruction for testing the docs

---

docs/proposal-rose-suite-run.md

Record the source directory in the "root" flow run directory as opposed to named run directory.
* This ensures all named runs are from the same installation source.
* Reinstallation knows where to install from.
* If we were to make the mandatory named run pattern optional this would be necessary to tell a named run from
a workflow.
I've proposed using `.cylc-install/source` to record this info, though happy to change this. Perhaps we should make this info more transparent on the FS?

rose suite-run: proposal amendment

---

docs/proposal-n-distance-window.md

Tried to write up the outcomes of several recent discussions about n-distance windowing here, to make sure we're all aware and agreed. 
The main concept and some details have already been accepted of course, but several sub-issues had not been thought through yet.  I've written it up from main concept down though for completeness, so we can extract documentation in future of the window users will see in the Cylc 8 UI.
The main new thing here is: how to handle satisfied tasks that are held back by xtriggers or queues etc. - these are not "active" (n=0) and they're not n=1 relative to current active tasks either, but they should not be invisible. I've argued here that the right thing to do is artificially add them to the n=1 window.
Added the main graph-window suspects as reviewers.

Add n-distance window proposal

---

docs/proposal-rose-suite-run.md
docs/proposal-universal-id.md

Adopt a universal identifier throughout all Cylc projects:
* Unblocks https://github.com/cylc/cylc-flow/issues/3592
* Solves the problem of `REG` being an optional positional argument *before* required positional arguments
(from the rose suite-run proposal).
* Provides a more powerful and simpler CLI.
* Clarifies to users whether commands are operating on the src or run directories.
Ping @dwsutherland

proposal: universal id

---

docs/index.md
docs/proposal-cylc-clean.md

> An outline of where we could go with the `cylc clean` command, very much open to ideas.
The current (Cylc7) approach to meddling with workflow files is a confusing trio of:
* `rose suite-clean`
* `rose_prune`
* `rose_arch`
These all have overlapping functionalities, they (ideally) *should* all:
* Locate workflow installations on different platforms (as required/configured).
* Have cycle awareness.
* Be able to perform cycle arithmetic.
* Be able to flush out files from within workflows
We wont get `cylc clean` up to `rose_arch` standards right away, nor should we, but we should be able to get some of the simpler cases out the way by early versions of Cylc8.
I would be keen for the development of a light-weight scaffold with plugins providing filetype support and archive functionality …

cylc clean proposal

---

README.md
docs/index.md

The idea being that the "question" label should be a flag for the cylc/core team to get involved.
We should shoehorn in a review of these open questions in each team meeting to try and avoid letting them build up too long.
Might take a little while to crack down on the number.

add link to open questions

---

.github/ISSUE_TEMPLATE/new-release.md

The issue template wasn't showing up because someone forgot to quote the title dammit.
I've added an extra step to specify the milestones, this gives us an issue count for each milestone which is quite useful.

fix issue template

---

.github/ISSUE_TEMPLATE/new-release.md

To accompany https://github.com/cylc/cylc-doc/pull/510

new release: add instruction to update changes page in cylc-doc

---

.github/wokflows/status.yml
.gitignore
docs/status/branches.json
docs/status/build
docs/status/template.md.jinja2

* Add a JSON file mapping component branches to meta releases.
This will save us having to maintain this list for each of the components individually.
* Add a status page generated from this to give better visibility of failures.
This can be used to automatically pick compatible Cylc versions for installation for CI in the Cylc component repositories via release-actions - https://github.com/cylc/release-actions/pull/46

add status page

---

.github/workflows/system.yml
docs/status/branches.json

> **Sibling:** https://github.com/cylc/release-actions/pull/48
* Partially addresses https://github.com/cylc/cylc-admin/issues/33
* Add a nightly build which installs the Cylc components for each supported Python version. This will help to detect metadata, dependency and branch conflict issues.
* Future work can add end-to-end tests which engage all of the system components.
This ensures the integrity of the branches.json file. Currently this action is failing due to cylc-rose branch conflict issues which is exactly the sort of error it is meant to flag.
~https://github.com/oliver-sanders/cylc-admin/actions/runs/4598273112~
new run with the latest diff: https://github.com/oliver-sanders/cylc-admin/actions/runs/4667619014/jobs/8265692353
FYI: The 8.2 tests will fail until - …

system tests

---

docs/proposal-cylc-set.md

Sorry, spotted a small error in the `cylc set` proposal.
`cylc set --pre=all` is NOT equivalent to trigger as outlined in "[7. Spawning parentless tasks](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-cylc-set.md#7-spawning-parentless-tasks)". It's more equivalent to Cylc 7's insert.

proposal set: fix small error

---

.github/workflows/status.yml

Workflow failed because we need to explicitly provide GITHUB_TOKEN as an environment variable.

fix status page

---

.github/ISSUE_TEMPLATE/new-release.md

Sorry, one more thing:
* Clarify the "bump downstream components" bit.
* Remove the now unnecessary "install-libs" bit (this is now done via a central action)

update release instructions
