- dec-workshop-agenda.md
Add (web) UI testing as discussion topic.
> Add (web) UI automated testing to list of discussion topics

- dec-workshop-agenda.md
I think there's some room for a short talk on Wednesday. Otherwise, feel free to move to another slot if that makes more sense :+1:
> Add a short talk about Docker and Cylc

- docs/cylc-8-roadmap.md
The six points from the June meeting.
> document benefits and motivation behind the new architecture

- docs/practices-prompts.md
Pre-register thoughts & key points regarding organisation & management of the 'Cylc (8) Road'.
I'm not sure what level of detail is appropriate as I do not know the extent to which new team members have been kept informed.
Hopefully this can be merged into the admin branch for people to read if they have a chance before the workshop begins, as this is material for the Monday.
> Add doc with working practice discussion prompts

- docs/cylc-8-tasks.md
I started tackling cylc/cylc#2651 (the basic conversion) yesterday afternoon, so to ensure nobody else begins this work please add my name by it in the task list. It's not critical work, but I think I might as well get it done, so it is not an interruption.
So far, I have got the Sphinx project set-up (& created a simple but very nice slightly-customised theme which I hope we will all like & agree to go with) & lifted & shifted the CUG & SDG. Once I get the LaTeX translated to reStructuredText I will open a WIP PR (estimate: early next week) & outline input needed by the team RE what to include, structure, theme etc.
> Report assignment to docs conversion

- docs/cylc-8-tasks.md
- docs/proposal-rose-suite-run.md
Bullet points on what's in scope for the `rose suite-run` migration activity.
> proposal draft: rose suite-run migration

- docs/dec-workshop-report.md
- docs/index.md
> Added 2018 workshop report.

- docs/cylc-8-tasks.md
Time estimate for Python 3 and packaging activities.
Add Rose Config-Edit.
Also fix typo *chartt* -> *chart*.
> cylc 8 gantt chart: more on Rose

- docs/meetings/vc-4-apr-2019-agenda.md
To save some time others can read it, and we can discuss or just skip this item in the meeting :+1:
> Status update about packaging

- docs/proposal-rose-suite-run.md
Add notes to rose suite-run migration proposal on rationalising settings in current configuration files.
See also https://github.com/cylc/cylc/issues/3098#issuecomment-481645024
> Proposal to rationalise configuration files

- docs/howto/environment.md
Address few issues after I have tried the instructions from scratch.
> Update HOWTO cylc-8

- docs/cylc-8-tasks.md
This is our Gantt Chart update from the final day in Exeter.
Any one reviewer will do!
> Projecttt Ganttt Charttt updattte.

- docs/howto/environment.md
Trying to keep my new starter guide to running cylc-ui/uiserver up-to date.
> Update beginner instructions for setting up Cylc UI on Conda

- docs/index.md
- docs/meetings/vc-9-aug-2019-summary.md
> Added 9 Aug meeting notes.

- docs/meetings/vc-9-sep-2019-agenda.md
Links broken for me, I think this fixes it?
Cheers
Bruno
> Fix links to previous month's meeting

- docs/howto/create-a-release.rst
- docs/index.md
A first draft only - the thoughts of others solicited.
I think we should check spelling and grammar and merge leaving debate on whether it works for PRs to come.
> some initial thoughts on creating a release

- docs/meetings/vc-8-oct-2019-agenda.md
Pointers to make it easy for people reading the agenda, and added a question on chages/changelogs for other projects.
Thanks
Bruno
> Update meeting agenda for 8-oct

- docs/proposal-rose-suite-run.md
- docs/rose-suite-run-proposal/cylc-flow-rc.md
Some updates on my plans for rose suite-run replacement based on actually getting my hands dirty with it.
Not sure that this needs an ultra thorough review, I'm just trying to keep the notes up-to-date.
> Update rose suite run replacement docs

- docs/meetings/vc-dec-2019-agenda.md
> Dec meeting agenda

- docs/index.md
- docs/meetings/dm-os-ho-17Dec2019.md
Ping @dpmatthews @oliver-sanders - so we don't forget what was discussed this morning.  Please sign off on this and merge (or let me know if I missed anything).
> Added OS NIWA meeting notes.

- docs/feb2020-workshop-agenda.md
Quick brain dump to get the ball rolling
(Suggest additions or changes by review here, or merge now then and post change PRs)
> 2020 workshop agenda rough cut

- docs/feb2020-workshop-agenda.md
> 2020 Workshop agenda update.

- docs/index.md
- docs/proposal-component-names.md
Let's see if we can finally lay this long-running discussion to rest.
Note this proposes one repository name change too (cylc-webui) for reasons explained in the document. Somewhat painful, but there will never be a better time than now.
@cylc/core - if anyone disagress with one or more of the marked (:boom:) changes at first glance, please read the relevant "Explanatory Comments" before deciding ... or else approve for merge.
Assigning everyone for this - if you don't have a strong opinion on it, just approve :grin: 
(Read with markdown rendered, via "View File" )
> Component naming proposal.

- docs/proposal-subscriptions.md
Proposal for how subscriptions could be handled at the UIS.
This is effectively a written form of the following diagram:
But with subscription examples which are loosely based on reality.
Please comment, feel free to raise larger changes as pull requests against this branch.
> proposal: subscription model

- docs/howto/cylc-ui.md
@oliver-sanders has advised me that developers probably want to install all optional dependencies - so I have updated my destructions.
> Minor update to getting started with the UI

- docs/proposal-spawn-on-d.md
@dpmatthews - putting this up as a PR so you can see the specific changes more easily (this is in response to our email discussion of a week or so ago).  I think I've addressed everything we covered.
That makes this document pretty comprehensive. I'd like to go back and make it is as concise as possible but probably not best use of my time at this point (I'll refine it for documentation purposes later on, once SoD is official :grin: ).
> SOD Proposal doc: addressed Dave's feedback.

- docs/howto/create-a-release.rst
This is for Cylc 8 only. Happy to amend, maybe shorten, etc, if required. I assumed it would be better to add as much detail first, then remove what others find is in excess :+1:
> Add Conda Forge release instructions

- docs/feb2020-workshop-notes.md
- docs/proposal-config-changes.md
See https://cylc.github.io/cylc-admin/feb2020-workshop-notes#wednesday
> Update config changes proposal based on CylcCon discussion

- docs/proposal-platforms.md
This covers:
* Installation of suites on platforms
* Symlinking of directories to different locations
> Platforms proposal: add details to the rose suite-run functionality

- docs/howto/create-a-release.md
Hopefully it will be helpful for future release-managers 👍
> Include information for future releases about troubleshooting conda releases

- docs/proposal-config-changes.md
- docs/proposal-platforms.md
Also fix a mistake in the config changes proposal.
> platforms proposal: make installation configurable at the suite level

- docs/proposal-spawn-on-d.md
(Following a conversation with @dpmatthews last night).
> Update SoD TODO list.

- docs/howto/testing.md
> how to debug pytest despite distribution

- docs/proposal-platforms.md
Modify proposal to specify symlink dirs per install target rather than per platform
> platforms proposal: specify symlink dirs per install target

- docs/howto/cylc-ui.md
> update dev docs

- docs/howto/cylc-ui.md
https://github.com/cylc/cylc-uiserver/pull/173
> dev: update ui/uis instructions

- docs/whats-new-in-c8.md
Merging this, to be improved and finished by subsequent PRs.
> Add a 'what's new in Cylc 8' doc.

- docs/whats-new-in-c8/whats-new-in-c8.md
I had a few thoughts about this - mostly small changes.
> Suggested small changes

- docs/howto/create-a-release.md
Goes with https://github.com/cylc/cylc-flow/pull/4197
> release workflow: add note about updating conda deps

- docs/index.md
- docs/proposal-new-output-syntax.md
> New optional output syntax proposal

- .github/ISSUE_TEMPLATE/new-release.md
> Added Issue template for new release steps.

- .github/ISSUE_TEMPLATE/new-release.md
- docs/howto/create-a-release.md
> update release template

- .github/ISSUE_TEMPLATE/new-release.md
> Added link to deploy instruction

- docs/index.md
- docs/project-issue-summary.md
I think this provides a useful summary of the project which we can refer to in the VCs.
Note that it will need updating as we close and open milestones but I'm happy to do this.
> Add project issue summary

- .github/ISSUE_TEMPLATE/new-release.md
Needs addition of auto-bumping dev version to the projects:
- cylc-flow (already done)
- https://github.com/cylc/cylc-uiserver/pull/391
- https://github.com/cylc/cylc-rose/pull/190
- https://github.com/metomi/rose/pull/2622
> Update release checklist

- docs/status/branches.json
- docs/status/build
- docs/status/template.md.jinja2
- Try using HTML table to see if that fixes render on GH Pages
- Fix cylc-flow listed workflows
> Fix status page

- docs/status/branches.json
Goeswith https://github.com/cylc/cylc-uiserver/pull/504
> bump UIS bugfix branch

- docs/proposal-optional-output-extension.md
A replacement for the optional outputs extension agreed in  #173.
> Modify the optional outputs extension proposal

- docs/proposal-optional-output-extension.md
Following on from our conversation the other day, here is a new amendment that I hope will satisfy all:
* Redefine task output "incompletion" to avoid problem edge cases.
* Permit pre-conditions in completion expressions.
* Remove redundent safety check that was only required for the previous proposal
* Remove references to task completion/incompletion in line with Hillary's preferences.
> amendment to proposal amendment

- .github/ISSUE_TEMPLATE/new-release.md
Something I've been doing for the last couple of releases that I think is worth continuing with.
> release: add note to announce new features on discourse

- docs/status/branches.json
* Remove 8.2 versions
* Add 8.4 versions
Obvs, we will need to create all those a.b.x branches.
> status: update versions

- docs/proposal-remove.md
Add missing context to clarify remove proposal statement.
See https://github.com/cylc/cylc-flow/pull/6472#discussion_r1838661893
> remove proposal clarification

- docs/status/branches.json
Build workflow recently added to metomi-rose.
> status: add new workflow

- docs/status/branches.json
> remove 8.4 meta-release

- docs/howto/dev-setup.md
https://wxtim.github.io/cylc-admin/howto/dev-setup
> Make Mermaid Work
